name: Manual workflow

on: 
  workflow_dispatch:

jobs:

  dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: https://dev.myapp.com
    steps:
      - name: deploy
        uses: actions/checkout@v2
      
