name: Manual workflow

on: 
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: https://dev.myapp.com
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: build
      
