name: Manual workflow

on:
  push:
    branches:
      -main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      
