name: Manual workflow

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        working-directory: ./CRUD-Angular
        run: npm install && npm run build 
      
